data:
    input_data: data_given/adm_data.csv
    raw_data: data/raw/adm_data.csv
    processed_data: data/processed/processed_data.csv

model_training:
    splitting params:
        random_state: 3
        split_size: 0.7
